runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: \1
  upload: (.*\.json)
  expiration: "1h"

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: \1
  upload: (.*\.otf)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: \1
  upload: (.*\.(svg|svgz))

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: \1
  upload: (.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: \1
  upload: (.*\.webp)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: \1
  upload: (.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: \1
  upload: (.*\.(bz2|gz|rar|tar|tgz|zip))
  
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: \1/index.html
  upload: (.+)/index.html
  expiration: "15m"
 
- url: /koi/
  static_files: \1/koi/index.html
  upload: (.*)/koi/index.html
  expiration: "15m"
  
# site root
- url: /
  static_files: index.html
  upload: index.html
  expiration: "15m"